version: '3'
services:
  db:
    image: mydb:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network
  app:
    image: myapp:latest
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - app_network
      - db_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  app_network:
    driver: overlay
  db_network:
    driver: overlay
volumes:
  db_data:
