---
- name: Install and configure Tomcat
  hosts: webservers
  become: yes
  vars_files:
    - tomcat-vars.yaml
  tasks:
    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Create Tomcat group
      group:
        name: tomcat
        state: present
    - name: Create Tomcat user
      user:
        name: tomcat
        group: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false
    - name: Download and extract Tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: /tmp
      become: yes
    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        owner: tomcat
        group: tomcat
        mode: "0755"
    - name: Wait for Tomcat extraction to complete
      pause:
        seconds: 30

- name: Enable and start Tomcat service
  hosts: webservers
  become: yes
  tasks:
    - name: Enable Tomcat service
      systemd:
        name: tomcat9
        enabled: yes
    - name: Start Tomcat service
      systemd:
        name: tomcat9
        state: started
    - name: Wait for Tomcat to start up before proceeding with the playbook.
      wait_for:
        host: localhost
        port: 8080
        delay: 30
        timeout: 300
